# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8e274e41abf18701e3db90a769841c080cd391b105f52133334e3afa8df822a53deda34726cacce0f7c4a102718cae495be4fc5cd261a7e97210d9a729a61e3

test:
  secret_key_base: 5cac773f424ab528e8a12a0773f775c834a92d78d8ea4f62bf1273a3e7d97db769329f113a8b11f509acc0edd1f9a1269fc177b94b34bba019cc27b929265d52

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
